export enum Role {
  ADMIN = 'ADMIN',
  CLUB_RESPONSABLE = 'CLUB_RESPONSABLE',
  JOUEUR = 'JOUEUR',
  STAFF_TECHNIQUE = 'STAFF_TECHNIQUE',
  STAFF_MEDICAL = 'STAFF_MEDICAL',
  FINANCIER = 'FINANCIER',
  SCOUT = 'SCOUT'
}
