export enum NotificationType {
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  MEDICAL_ALERT = 'MEDICAL_ALERT',
  TRAINING_REMINDER = 'TRAINING_REMINDER',
  EMERGENCY = 'EMERGENCY',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  SYSTEM = 'SYSTEM'
}
