export enum Permission {
  CLUBS_PENDING_READ = 'clubs.pending.read',
  CLUBS_APPROVE = 'clubs.approve',
  USERS_PENDING_READ = 'users.pending.read',
  USERS_APPROVE = 'users.approve',
  USERS_READ = 'users.read',
  USERS_UPDATE = 'users.update',
  USERS_DELETE = 'users.delete',
  FINANCE_ACCOUNTING_CREATE = 'finance.accounting.create',
  FINANCE_ACCOUNTING_READ = 'finance.accounting.read',
  FINANCE_PAYROLL_PREVIEW = 'finance.payroll.preview',
  FINANCE_PAYROLL_EXECUTE = 'finance.payroll.execute',
  FINANCE_TRANSFERS_CREATE = 'finance.transfers.create',
  FINANCE_TRANSFERS_PAY = 'finance.transfers.pay',
  FINANCE_TREASURY_READ = 'finance.treasury.read',
  FINANCE_TREASURY_RECONCILE = 'finance.treasury.reconcile',
  FINANCE_BUDGET_READ = 'finance.budget.read',
  FINANCE_BUDGET_EDIT = 'finance.budget.edit',
  FINANCE_REPORTS_GENERATE = 'finance.reports.generate',
  FINANCE_AUDIT_READ = 'finance.audit.read'
}
