const { MongoClient } = require('mongodb');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017';
const DB_NAME = process.env.DB_NAME || 'odin_backend';
const SEED_SOURCE = 'manual-real-seed-v1';

const players = [
  // Goalkeepers (3)
  {
    providerPlayerId: 'gk-courtois',
    name: 'Thibaut Courtois',
    firstName: 'Thibaut',
    lastName: 'Courtois',
    age: 33,
    position: 'GK',
    strongFoot: 'Left',
    jerseyNumber: 1,
    height: 200,
    weight: 96,
    nationality: 'Belgium',
    speed: 48,
    endurance: 71,
    distance: 6.1,
    dribbles: 0,
    shots: 0,
    injuries: 0,
    heart_rate: 68,
    baseFitness: 84,
  },
  {
    providerPlayerId: 'gk-ederson',
    name: 'Ederson Moraes',
    firstName: 'Ederson',
    lastName: 'Moraes',
    age: 32,
    position: 'GK',
    strongFoot: 'Left',
    jerseyNumber: 31,
    height: 188,
    weight: 86,
    nationality: 'Brazil',
    speed: 50,
    endurance: 73,
    distance: 6.4,
    dribbles: 1,
    shots: 0,
    injuries: 0,
    heart_rate: 69,
    baseFitness: 85,
  },
  {
    providerPlayerId: 'gk-donnarumma',
    name: 'Gianluigi Donnarumma',
    firstName: 'Gianluigi',
    lastName: 'Donnarumma',
    age: 27,
    position: 'GK',
    strongFoot: 'Right',
    jerseyNumber: 99,
    height: 196,
    weight: 90,
    nationality: 'Italy',
    speed: 49,
    endurance: 72,
    distance: 6.2,
    dribbles: 0,
    shots: 0,
    injuries: 0,
    heart_rate: 68,
    baseFitness: 86,
  },

  // Defenders (7)
  {
    providerPlayerId: 'def-hakimi',
    name: 'Achraf Hakimi',
    firstName: 'Achraf',
    lastName: 'Hakimi',
    age: 27,
    position: 'RB',
    strongFoot: 'Right',
    jerseyNumber: 2,
    height: 181,
    weight: 73,
    nationality: 'Morocco',
    speed: 93,
    endurance: 88,
    distance: 11.2,
    dribbles: 28,
    shots: 10,
    injuries: 0,
    heart_rate: 76,
    baseFitness: 90,
  },
  {
    providerPlayerId: 'def-van-dijk',
    name: 'Virgil van Dijk',
    firstName: 'Virgil',
    lastName: 'van Dijk',
    age: 35,
    position: 'CB',
    strongFoot: 'Right',
    jerseyNumber: 4,
    height: 193,
    weight: 92,
    nationality: 'Netherlands',
    speed: 78,
    endurance: 84,
    distance: 9.0,
    dribbles: 7,
    shots: 5,
    injuries: 0,
    heart_rate: 74,
    baseFitness: 87,
  },
  {
    providerPlayerId: 'def-ruben-dias',
    name: 'Ruben Dias',
    firstName: 'Ruben',
    lastName: 'Dias',
    age: 29,
    position: 'CB',
    strongFoot: 'Right',
    jerseyNumber: 3,
    height: 187,
    weight: 82,
    nationality: 'Portugal',
    speed: 74,
    endurance: 84,
    distance: 8.7,
    dribbles: 6,
    shots: 4,
    injuries: 0,
    heart_rate: 73,
    baseFitness: 86,
  },
  {
    providerPlayerId: 'def-saliba',
    name: 'William Saliba',
    firstName: 'William',
    lastName: 'Saliba',
    age: 25,
    position: 'CB',
    strongFoot: 'Right',
    jerseyNumber: 2,
    height: 192,
    weight: 83,
    nationality: 'France',
    speed: 80,
    endurance: 85,
    distance: 8.9,
    dribbles: 9,
    shots: 3,
    injuries: 0,
    heart_rate: 73,
    baseFitness: 88,
  },
  {
    providerPlayerId: 'def-alphonso-davies',
    name: 'Alphonso Davies',
    firstName: 'Alphonso',
    lastName: 'Davies',
    age: 26,
    position: 'LB',
    strongFoot: 'Left',
    jerseyNumber: 19,
    height: 183,
    weight: 75,
    nationality: 'Canada',
    speed: 96,
    endurance: 89,
    distance: 11.4,
    dribbles: 32,
    shots: 8,
    injuries: 0,
    heart_rate: 77,
    baseFitness: 90,
  },
  {
    providerPlayerId: 'def-theo-hernandez',
    name: 'Theo Hernandez',
    firstName: 'Theo',
    lastName: 'Hernandez',
    age: 29,
    position: 'LB',
    strongFoot: 'Left',
    jerseyNumber: 19,
    height: 184,
    weight: 81,
    nationality: 'France',
    speed: 91,
    endurance: 87,
    distance: 11.0,
    dribbles: 27,
    shots: 9,
    injuries: 0,
    heart_rate: 76,
    baseFitness: 89,
  },
  {
    providerPlayerId: 'def-gvardiol',
    name: 'Josko Gvardiol',
    firstName: 'Josko',
    lastName: 'Gvardiol',
    age: 24,
    position: 'CB',
    strongFoot: 'Left',
    jerseyNumber: 24,
    height: 185,
    weight: 80,
    nationality: 'Croatia',
    speed: 79,
    endurance: 84,
    distance: 9.1,
    dribbles: 10,
    shots: 4,
    injuries: 0,
    heart_rate: 74,
    baseFitness: 87,
  },

  // Midfielders (7)
  {
    providerPlayerId: 'mid-rodri',
    name: 'Rodri',
    firstName: 'Rodri',
    lastName: 'Hernandez',
    age: 30,
    position: 'CDM',
    strongFoot: 'Right',
    jerseyNumber: 16,
    height: 191,
    weight: 82,
    nationality: 'Spain',
    speed: 71,
    endurance: 92,
    distance: 12.0,
    dribbles: 14,
    shots: 11,
    injuries: 0,
    heart_rate: 75,
    baseFitness: 91,
  },
  {
    providerPlayerId: 'mid-bellingham',
    name: 'Jude Bellingham',
    firstName: 'Jude',
    lastName: 'Bellingham',
    age: 23,
    position: 'CM',
    strongFoot: 'Right',
    jerseyNumber: 5,
    height: 186,
    weight: 75,
    nationality: 'England',
    speed: 82,
    endurance: 90,
    distance: 11.5,
    dribbles: 35,
    shots: 22,
    injuries: 0,
    heart_rate: 76,
    baseFitness: 92,
  },
  {
    providerPlayerId: 'mid-de-bruyne',
    name: 'Kevin De Bruyne',
    firstName: 'Kevin',
    lastName: 'De Bruyne',
    age: 35,
    position: 'CAM',
    strongFoot: 'Right',
    jerseyNumber: 17,
    height: 181,
    weight: 70,
    nationality: 'Belgium',
    speed: 74,
    endurance: 84,
    distance: 10.2,
    dribbles: 22,
    shots: 18,
    injuries: 1,
    heart_rate: 74,
    baseFitness: 86,
  },
  {
    providerPlayerId: 'mid-valverde',
    name: 'Federico Valverde',
    firstName: 'Federico',
    lastName: 'Valverde',
    age: 27,
    position: 'CM',
    strongFoot: 'Right',
    jerseyNumber: 8,
    height: 182,
    weight: 78,
    nationality: 'Uruguay',
    speed: 84,
    endurance: 93,
    distance: 12.4,
    dribbles: 19,
    shots: 16,
    injuries: 0,
    heart_rate: 77,
    baseFitness: 92,
  },
  {
    providerPlayerId: 'mid-pedri',
    name: 'Pedri',
    firstName: 'Pedro',
    lastName: 'Gonzalez',
    age: 23,
    position: 'CM',
    strongFoot: 'Right',
    jerseyNumber: 8,
    height: 174,
    weight: 60,
    nationality: 'Spain',
    speed: 79,
    endurance: 86,
    distance: 11.0,
    dribbles: 41,
    shots: 10,
    injuries: 0,
    heart_rate: 75,
    baseFitness: 89,
  },
  {
    providerPlayerId: 'mid-declan-rice',
    name: 'Declan Rice',
    firstName: 'Declan',
    lastName: 'Rice',
    age: 27,
    position: 'CDM',
    strongFoot: 'Right',
    jerseyNumber: 41,
    height: 188,
    weight: 80,
    nationality: 'England',
    speed: 77,
    endurance: 91,
    distance: 12.1,
    dribbles: 17,
    shots: 9,
    injuries: 0,
    heart_rate: 76,
    baseFitness: 91,
  },
  {
    providerPlayerId: 'mid-bruno-fernandes',
    name: 'Bruno Fernandes',
    firstName: 'Bruno',
    lastName: 'Fernandes',
    age: 32,
    position: 'CAM',
    strongFoot: 'Right',
    jerseyNumber: 8,
    height: 179,
    weight: 69,
    nationality: 'Portugal',
    speed: 72,
    endurance: 90,
    distance: 11.8,
    dribbles: 20,
    shots: 19,
    injuries: 0,
    heart_rate: 75,
    baseFitness: 90,
  },

  // Attackers (7)
  {
    providerPlayerId: 'att-mbappe',
    name: 'Kylian Mbappe',
    firstName: 'Kylian',
    lastName: 'Mbappe',
    age: 28,
    position: 'LW',
    strongFoot: 'Right',
    jerseyNumber: 9,
    height: 178,
    weight: 75,
    nationality: 'France',
    speed: 97,
    endurance: 88,
    distance: 10.9,
    dribbles: 52,
    shots: 41,
    injuries: 0,
    heart_rate: 77,
    baseFitness: 92,
  },
  {
    providerPlayerId: 'att-haaland',
    name: 'Erling Haaland',
    firstName: 'Erling',
    lastName: 'Haaland',
    age: 26,
    position: 'ST',
    strongFoot: 'Left',
    jerseyNumber: 9,
    height: 194,
    weight: 88,
    nationality: 'Norway',
    speed: 89,
    endurance: 84,
    distance: 10.1,
    dribbles: 14,
    shots: 48,
    injuries: 0,
    heart_rate: 75,
    baseFitness: 90,
  },
  {
    providerPlayerId: 'att-vinicius',
    name: 'Vinicius Junior',
    firstName: 'Vinicius',
    lastName: 'Junior',
    age: 25,
    position: 'LW',
    strongFoot: 'Right',
    jerseyNumber: 7,
    height: 176,
    weight: 73,
    nationality: 'Brazil',
    speed: 95,
    endurance: 87,
    distance: 10.8,
    dribbles: 56,
    shots: 26,
    injuries: 0,
    heart_rate: 77,
    baseFitness: 91,
  },
  {
    providerPlayerId: 'att-salah',
    name: 'Mohamed Salah',
    firstName: 'Mohamed',
    lastName: 'Salah',
    age: 34,
    position: 'RW',
    strongFoot: 'Left',
    jerseyNumber: 11,
    height: 175,
    weight: 71,
    nationality: 'Egypt',
    speed: 91,
    endurance: 88,
    distance: 10.7,
    dribbles: 43,
    shots: 30,
    injuries: 0,
    heart_rate: 76,
    baseFitness: 90,
  },
  {
    providerPlayerId: 'att-saka',
    name: 'Bukayo Saka',
    firstName: 'Bukayo',
    lastName: 'Saka',
    age: 25,
    position: 'RW',
    strongFoot: 'Left',
    jerseyNumber: 7,
    height: 178,
    weight: 72,
    nationality: 'England',
    speed: 90,
    endurance: 89,
    distance: 11.1,
    dribbles: 38,
    shots: 24,
    injuries: 0,
    heart_rate: 76,
    baseFitness: 91,
  },
  {
    providerPlayerId: 'att-lautaro',
    name: 'Lautaro Martinez',
    firstName: 'Lautaro',
    lastName: 'Martinez',
    age: 29,
    position: 'ST',
    strongFoot: 'Right',
    jerseyNumber: 10,
    height: 174,
    weight: 72,
    nationality: 'Argentina',
    speed: 84,
    endurance: 86,
    distance: 10.2,
    dribbles: 20,
    shots: 35,
    injuries: 0,
    heart_rate: 75,
    baseFitness: 89,
  },
  {
    providerPlayerId: 'att-osimhen',
    name: 'Victor Osimhen',
    firstName: 'Victor',
    lastName: 'Osimhen',
    age: 28,
    position: 'ST',
    strongFoot: 'Right',
    jerseyNumber: 9,
    height: 186,
    weight: 78,
    nationality: 'Nigeria',
    speed: 90,
    endurance: 86,
    distance: 10.4,
    dribbles: 16,
    shots: 33,
    injuries: 0,
    heart_rate: 75,
    baseFitness: 90,
  },
];

async function run() {
  const client = new MongoClient(MONGO_URI);

  try {
    await client.connect();
    const db = client.db(DB_NAME);
    const collection = db.collection('players');

    let upserted = 0;
    let modified = 0;

    for (const player of players) {
      const now = new Date();
      const filter = {
        providerName: SEED_SOURCE,
        providerPlayerId: player.providerPlayerId,
      };

      const result = await collection.updateOne(
        filter,
        {
          $set: {
            ...player,
            providerName: SEED_SOURCE,
            status: 'active',
            updatedAt: now,
          },
          $setOnInsert: {
            createdAt: now,
            injuryHistory: 0,
            isInjured: false,
            label: 1,
          },
        },
        { upsert: true }
      );

      if (result.upsertedCount > 0) {
        upserted += result.upsertedCount;
      }
      if (result.modifiedCount > 0) {
        modified += result.modifiedCount;
      }
    }

    const seededCount = await collection.countDocuments({ providerName: SEED_SOURCE });

    console.log('Real players seed completed.');
    console.log(`Source: ${SEED_SOURCE}`);
    console.log(`Inserted: ${upserted}`);
    console.log(`Updated: ${modified}`);
    console.log(`Total players from this seed in DB: ${seededCount}`);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exitCode = 1;
  } finally {
    await client.close();
  }
}

run();
